import pandas as pd
import json
import ast
import re
import os
import argparse
import pickle
##LOAD all related tools
from langchain_mcp_adapters.tools import load_mcp_tools
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from tenacity import AsyncRetrying, stop_after_attempt, wait_exponential
from datetime import datetime

##define the generation part
import asyncio
from mcp.types import Notification
from OSCAR_main import create_chemistry_app
import logging

##Basic log configuration: INFO level, includes timestamp, module name, level, and message
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

server_params = StdioServerParameters(
    command="python",
    args=["-u", "./mcp_tools/mcp_rag.py"],
)

config = {
    "configurable": {"thread_id": "1"}, # Standard config
    "max_concurrency": 8                # Limit to 2 parallel tasks at a time
}

def resolve_index_range(start_index, end_index, shard_id, num_shards, total_records):
    if (shard_id is None) != (num_shards is None):
        raise ValueError("--shard_id and --num_shards must be provided together")
    if shard_id is not None:
        if total_records is None:
            raise ValueError("--total_records is required when using --shard_id/--num_shards")
        if shard_id < 0 or shard_id >= num_shards:
            raise ValueError("--shard_id must be in [0, num_shards)")
        records_per_shard = (total_records + num_shards - 1) // num_shards
        start_index = shard_id * records_per_shard
        end_index = min(total_records, (shard_id + 1) * records_per_shard)
    return start_index, end_index


def _split_smiles_components(smiles_text):
    return [
        part.strip()
        for part in str(smiles_text or "").split(".")
        if part.strip()
    ]


def _entries_from_smiles(smiles_text, name_prefix, default_key):
    entries = []
    for idx, smiles in enumerate(_split_smiles_components(smiles_text), start=1):
        entry = {
            "name": f"{name_prefix}_{idx}",
            "smiles": smiles,
        }
        entry[default_key] = 1.0
        entries.append(entry)
    return entries


def _condition_field(condition, field):
    match = re.search(
        field + r"\s*:\s*(.*?)(?:\s+(?:reagents|solvents|catalysts|temperature|time)\s*:|$)",
        str(condition or ""),
        flags=re.I,
    )
    return match.group(1).strip() if match else ""


def _has_reaction_conditions(recipe):
    if not isinstance(recipe, dict):
        return False
    reaction_conditions = recipe.get("reaction_conditions")
    if not isinstance(reaction_conditions, dict):
        return False
    reactants = reaction_conditions.get("reactants")
    return isinstance(reactants, list) and len(reactants) > 0


def _fallback_recipe_from_local_pathway(pathway, product_smiles):
    pathway = pathway if isinstance(pathway, dict) else {}
    reactants = pathway.get("reactants", "")
    condition = pathway.get("condition", "")
    reagents = _condition_field(condition, "reagents")
    solvents = _condition_field(condition, "solvents")
    return {
        "reaction_name": "Local model fallback recipe",
        "recommendation_and_ranking": {
            "ranking": pathway.get("pathway_id"),
            "rationale": (
                "Agent recipe JSON was empty or invalid, so this recipe was "
                "constructed from the local model pathway to preserve evaluable "
                "reactants and conditions."
            ),
            "confidence_score": 1,
        },
        "reactant_revision": {
            "changed": False,
            "original_reactants": reactants,
            "final_reactants": reactants,
            "alternative_reactants": [],
            "policy_note": "Fallback generated by run_app.py because agent recipe was empty.",
        },
        "reaction_conditions": {
            "reactants": _entries_from_smiles(reactants, "local_reactant", "equivalents"),
            "reagents": _entries_from_smiles(reagents, "local_reagent", "equivalents"),
            "solvents": _entries_from_smiles(solvents, "local_solvent", "volume"),
            "temperature": None,
            "time": None,
        },
        "procedure": (
            "Fallback recipe generated from the local model prediction. "
            f"Target product: {product_smiles}."
        ),
    }


def _extract_recipe_from_report(report):
    pattern = r"```json\s*(\{.*?\})\s*```"
    match = re.search(pattern, str(report or ""), re.DOTALL)
    if not match:
        return None
    json_str = match.group(1).strip()
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        try:
            return ast.literal_eval(json_str)
        except Exception:
            return None


async def main(
    prefix_checkpoint="tmpxx_",
    input_file="evaluate/500_samples_March31_6_rag_agentic.csv",
    output_file="./evaluate/April13_retry5_top1_llama3_8b_whole_recipes_100",
    simple_rag=False,
    generate_only=False,
    num_samples=1,
    start_index=0,
    end_index=None,
    shard_id=None,
    num_shards=None,
    total_records=None,
    max_concurrency=8,
):
    start_index, end_index = resolve_index_range(
        start_index=start_index,
        end_index=end_index,
        shard_id=shard_id,
        num_shards=num_shards,
        total_records=total_records,
    )
    to_save = f"{output_file}.pkl"
    to_save_jsonl = f"{output_file}.json"
    output_dir = os.path.dirname(os.path.abspath(output_file))
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    checkpoint_dir = os.path.dirname(os.path.abspath(prefix_checkpoint))
    if checkpoint_dir:
        os.makedirs(checkpoint_dir, exist_ok=True)
    logger.info(
        "模型=%s | 时间=%s | num_samples=%s | max_concurrency=%s | range=(%s, %s]",
        os.getenv("SOTA_MODEL", "gemini-2.5-pro"),
        datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        num_samples,
        max_concurrency,
        start_index,
        end_index,
    )
    run_config = {
        "configurable": {"thread_id": str(prefix_checkpoint)},
        "max_concurrency": max_concurrency,
    }
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            
            # 2. Notify the server you are ready (mandatory for most 2026 SDKs)
            # Without this, some servers close the connection thinking the client hung
            await session.send_notification(Notification(method="notifications/initialized",params={}))
            
            # 2. Load the MCP tools (this includes retrieve_docs)
            mcp_tools = await load_mcp_tools(session)
            logger.info("✅ Tools Loaded: %s", [t.name for t in mcp_tools])            
            mcp_retrieve = next(t for t in mcp_tools if t.name == "search_similar_reactions")
            # 1. Locate the new tool from the loaded MCP tools list
            mcp_refiner = next(t for t in mcp_tools if t.name == "execute_synthesis_refinement")
            
            # 3. Create the App (Separated logic)
            app = create_chemistry_app(mcp_retrieve, mcp_refiner, num_samples=num_samples, simple_rag=simple_rag, generate_only=generate_only)



            #image_data = app.get_graph().draw_mermaid_png()
            #with open("my_agent_graph.png", "wb") as f:
            #    f.write(image_data)

            #define inputs and retrieval, generate, return result
            sample_inputs = [{
                "messages": [("user", "What are the common conditions for this reaction?")],
                "products_SMILES": "COc1cncc2c1[C@]1(O)[C@H](O)[C@H](C(N)=O)[C@@H](c3ccccc3)[C@]1(c1ccc(Br)cc1)O2",
            },
                      {"messages": [("user", "What are the common conditions for this reaction?")],
                "products_SMILES": "COc1cncc2c1[C@]1(O)[C@H](O)[C@H](C(N)=O)[C@@H](c3ccccc3)[C@]1(c1ccc(Br)cc1)O2",
            }]
            test_500 = pd.read_csv(input_file) #500_samples_rag_agentic.csv")
            sample_inputs = []
            count = 0
            #read checkpoint file
            checkpoint_file = f"{prefix_checkpoint}_checkpoint.json"
            #start_idx = 56
            # 1. LOAD CHECKPOINT
            if os.path.exists(checkpoint_file):
                with open(checkpoint_file, "r") as f:
                    checkpoint = json.load(f)
                    start_idx = max(start_index, checkpoint.get("last_index", 0))
                    print(f"🔄 Resuming from checkpoint at index {start_idx}")
            else:
                start_idx = start_index # Or your desired default starting point
                print(f"🆕 Starting fresh run from index {start_idx}") 
            for row in test_500.itertuples():
                count += 1
                if count <= start_idx:
                    continue
                if end_index is not None and count > end_index:
                    break
                #print(f"current row is {row} and products canonical final one is {row.s_reactants}")
                products_s = row.s_products
                reactants_s = row.s_reactants
                solvents_s = row.s_solvents
                reagents_s = row.s_reagents
                #print(f"DEBUG SHAN clean reponse part is {row.clean_response} and type is {type(row.clean_response)}")
                data = ast.literal_eval(row.clean_response)
                #print(type(data))           # Output: <class 'list'>
                #print(data[0]['yield'])     # Output: 73% over 3 steps
                #print(data[0]['is_multi_stage']) # Output: False (as a boolean)
                #products_iupac = json.load(row.clean_response)
                #assert 0""
                sample_inputs.append({
                    "messages": [("user", "What are the common conditions for this reaction?")],
                "products_SMILES": products_s,
                })
                inputs = {
                    "messages": [("user", "What are the common conditions for this reaction?")],
                "products_SMILES": products_s,
                "num_samples": num_samples,
                }
                try:# RETRY LOGIC FOR THE BATCH
                    async for attempt in AsyncRetrying(
                        stop=stop_after_attempt(5),
                        wait=wait_exponential(multiplier=1, min=4, max=60),
                        reraise=True
                    ):
                        with attempt:
                            print(f"🚀 Processing batch {start_idx}-{count} (Attempt {attempt.retry_state.attempt_number})")
                            result = await app.ainvoke(inputs, run_config)
                            logger.info("%s", result["messages"][-1].content)
                            val_errors = result.get("validation_errors", [])
                            failed_ids = {
                                e["pathway_id"]
                                for e in val_errors
                                if e.get("type") != "success"
                            }
                            final_recipes = []
                            pathways = result.get("pathways", [])
                            pathway_ids = result.get("pathway_id", [])
                            final_reports = result.get("final_reports", [])
                            for i, curr in enumerate(final_reports):
                                pid = pathway_ids[i] if i < len(pathway_ids) else i
                                data = _extract_recipe_from_report(curr)
                                if not _has_reaction_conditions(data):
                                    local_pathway = pathways[pid] if isinstance(pid, int) and pid < len(pathways) else (
                                        pathways[i] if i < len(pathways) else {}
                                    )
                                    data = _fallback_recipe_from_local_pathway(
                                        local_pathway,
                                        products_s,
                                    )
                                    logger.warning(
                                        "Agent recipe empty/invalid for idx=%s pathway_id=%s; "
                                        "using local fallback recipe.",
                                        count,
                                        pid,
                                    )
                                final_recipes.append(data)

                            while len(final_recipes) < len(pathways):
                                i = len(final_recipes)
                                final_recipes.append(
                                    _fallback_recipe_from_local_pathway(pathways[i], products_s)
                                )
                            entry = {
                                "idx": count,   #the index among all 500 samples
                                "k": row.k,
                                "patent_details": row.v,
                                "patent_products": products_s,
                                "patent_reactants": reactants_s,
                                "patent_reagents": reagents_s,
                                "patent_solvents": solvents_s,
                                "pathways": result["pathways"],
                                "pathway_id": result["pathway_id"],
                                "retrieval_first": result["top5_retrieval"],
                                "top3_rerank_retrieval":result["top3_rerank_retrieval"],
                                "top3_rerank_extract":result["top3_rerank_extract"],
                                "validation_errors": val_errors,
                                "failed_pathway_ids": list(failed_ids),
                                "full_recipe": final_recipes,
                                "final_reports": result["final_reports"],
                                "history": result.get("history", []),
                            }
                            with open(to_save, "ab") as f:
                                pickle.dump(entry, f)
                            with open(to_save_jsonl, 'a', encoding='utf-8') as f:
                                f.write(json.dumps(entry, indent=4) + '\n')
                            # Increment index and save progress to JSON
                            start_idx = count
                            with open(checkpoint_file, "w") as f:
                                json.dump({"last_index": start_idx}, f)
                    print(f"✅ Batch complete. Checkpoint updated to {count}.")
                except Exception as e:
                    print(f"❌ Batch starting at {count} failed permanently: {e}")
                    break

                if end_index is not None and count >= end_index:
                    print("🏁 All samples processed. Deleting checkpoint.")
                    if os.path.exists(checkpoint_file):
                        os.remove(checkpoint_file)
                    break
    
# Entry point to run the async code
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="A simple addition script")
    parser.add_argument("-f", "--input_file", type=str, help="the input csv file to process to get the corresponding reaction protocal")
    parser.add_argument("-s", "--output_file", type=str, help="the output json and pkl prefix file path")
    parser.add_argument("-p", "--prefix", type=str, help="the running prefix_checkepoint")
    parser.add_argument("--generate_only", action="store_true", help="Discard whole retreieval part for ablation experiment")
    parser.add_argument("--simple_rag", action="store_true", help="Run the agent with simple GNN retrieval without rerank")
    parser.add_argument("--num_samples",type=int, help="run pathway num_samples", default=1)
    parser.add_argument("--start_index", type=int, default=0, help="1-based record count lower bound already completed; process records with count > start_index")
    parser.add_argument("--end_index", type=int, default=None, help="1-based inclusive record count upper bound to process")
    parser.add_argument("--shard_id", type=int, default=None, help="0-based shard id for distributed inference")
    parser.add_argument("--num_shards", type=int, default=None, help="number of distributed inference shards")
    parser.add_argument("--total_records", type=int, default=None, help="total records to split when using shard mode")
    parser.add_argument("--max_concurrency", type=int, default=8, help="LangGraph max_concurrency inside each run_app process")
    args = parser.parse_args()
    in_file = args.input_file
    out_file = args.output_file
    prefix = args.prefix
    simple_rag = args.simple_rag
    num_samples = args.num_samples
    asyncio.run(main(
        prefix_checkpoint=prefix,
        input_file=in_file,
        output_file=out_file,
        simple_rag=simple_rag,
        generate_only=args.generate_only,
        num_samples=num_samples,
        start_index=args.start_index,
        end_index=args.end_index,
        shard_id=args.shard_id,
        num_shards=args.num_shards,
        total_records=args.total_records,
        max_concurrency=args.max_concurrency,
    ))
